version: '3.8'

services:
  mysql-db:
    container_name: mysql-golfclub
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: golfclub
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: golfclub-api
    build: .
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://golfclub.cp0wok6ks0cy.ca-central-1.rds.amazonaws.com/golfclub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret123
    ports:
      - "8080:8080"

volumes:
  mysql_data:
